### ISSUE TITLE
高频考点之计算机网络

### ISSUE THREAD

**Issue by turkyden** [turkyden/turkyden#16]
## 高频考点

- [ ] HTTP 缓存
- [ ] HTTP 常用的状态码及使用场景？302 用过吗？
- [ ] HTTP 常用的请求方式，区别和用途？
- [ ] 你对计算机网络的认识怎么样？
- [ ] HTTPS 是什么？具体流程
- [x] 三次握手和四次挥手？为什么不是两次？
- [ ] 在交互过程中如果数据传送完了，还不想断开连接怎么办，怎么维持？
- [x] 你对 TCP 滑动窗口有了解嘛？
- [ ] WebSocket 与 Ajax 的区别
- [ ] HTTP 如何实现长连接？在什么时候会超时？
- [ ] 了解 WebSocket 嘛？
- [ ] Fetch API 与传统 Request 的区别？
- [ ] POST 一般可以发送什么类型的文件？
- [ ] TCP 如何保证有效传输及拥塞控制原理？
- [ ] OPTION 是干啥的？举个用到 OPTION 的例子？
- [x] http 知道嘛 ？哪一层的协议？
- [x] OSI 七层模型和 TCP/IP 四层模型？
- [ ] TCP 协议怎么保证可靠的，UDP 为什么不可靠？
- [ ] HTTP 2 改进

## 参考

- [[1] 字节跳动最爱考的前端面试题：计算机网络基础](https://juejin.cn/post/6939691851746279437)
- [[2] 可能是全网最全的http面试答案](https://juejin.cn/post/6844903865410650126)

**Comment by Turkyden** [comment]
## 从输入 URL 后到页面展现发生了什么？

**Comment by Turkyden** [comment]
TCP/IP 五层协议

- 应用层 http
- 传输层 tcp 
- 网络层 ip
- 数据链路层
- 物理层

**Comment by Turkyden** [comment]
![image](https://user-images.githubusercontent.com/24560160/116812948-f1291900-ab83-11eb-9e2e-55b689d902ef.png)

**Comment by Turkyden** [comment]
DNS 解析过程 https://www.youtube.com/watch?v=Wj0od2ag5sk

![image](https://user-images.githubusercontent.com/24560160/116813454-7b727c80-ab86-11eb-82a3-2668f4db573f.png)

**Comment by Turkyden** [comment]
> 你对 TCP 滑动窗口有了解嘛？

滑动窗口是 TCP 协议控制可靠性的核心，发送方将数据拆包，变成多个分组，然后将数据放入一个拥有滑动窗口的数组，依次发出，仍然遵循先进先出（FIFO）的顺序，但是窗口中的分组会一次性发送。窗口中序号最小的分组如果接受到 ACK，窗口就会发生滑动，如果最小序号的分组长时间没有接收到 ACK，就会触发整个窗口的数据重新发送。
