### ISSUE TITLE
高频考点之 JavaScript 基础

### ISSUE THREAD

**Issue by turkyden** [turkyden/turkyden#17]
## 高频考点

- [ ] 0.1 + 0.2 === 0.3 嘛？为什么？
- [ ] JS 数据类型
- [ ] JS 整数是怎么表示的？
- [ ] Number() 的存储空间是多大？如果后台发送了一个超过最大自己的数字怎么办
- [ ] 写代码：实现函数能够深度克隆基本类型
- [ ] 事件流，事件捕获，事件冒泡
- [ ] 事件是如何实现的？手写发布订阅
- [ ] new 一个函数发生了什么？
- [ ] new 一个构造函数，如果函数返回 return {} 、 return null ， return 1 ， return true 会发生什么情况？
- [ ] symbol 有什么用处？
- [ ] 闭包是什么？什么是作用域？什么是作用域链？一般如何产生闭包？应用场景？
- [ ] NaN 是什么，用 typeof 会输出什么？
- [ ] JS 隐式转换，显示转换
- [ ] 了解 this 嘛，bind，call，apply 具体指什么？手写 bind、apply、call ？
- [ ] setTimeout(fn, 0) 多久才执行，Event Loop 事件循环
- [ ] 手写 Promise
- [ ] js 脚本加载问题，async、defer 问题
- [ ] 如何判断一个对象是不是空对象？
- [ ] 手写 getUrlParams(url,key); 需要考虑边界情况，多个返回值
- [ ] <script src=’xxx’ ’xxx’/> 外部 js 文件先加载还是 onload 先执行，为什么？
- [x] 怎么加事件监听，两种？onclick 和 addEventListener
- [ ] 事件传播机制，冒泡和捕获
- [ ] 说一下原型链和原型链的继承吧
- [x] 说下对 JS 的了解吧？
- [x] 数组能够调用的函数有那些？
- [x] 如何判断数组类型？Array.isArray
- [x] 函数中的 arguments 是数组吗？类数组转数组的方法了解吗？
- [x] 用过 TypeScript 吗？它的作用是什么？
- [ ] PWA 使用过吗？serviceWorker 的使用原理是啥？
- [ ] ES6 之前使用 prototype 实现继承
- [ ] 如果一个构造函数，bind了一个对象，用这个构造函数创建出的实例会继承这个对象的属性吗？为什么？
- [ ] 箭头函数和普通函数有啥区别？箭头函数能当构造函数吗？
- [ ] 知道 ES6 的 Class 嘛？Static 关键字有了解嘛
- [ ] 事件循环机制 （Event Loop）
- [ ] 手写题：数组扁平化
- [ ] 手写题：实现柯里化
- [ ] 手写题：数组去重
- [ ] let 闭包
- [ ] 变量提升
- [ ] instance 如何使用

## 参考资料

- [[1] 字节跳动最爱考的前端面试题：JavaScript 基础](https://juejin.cn/post/6934500357091360781)

**Comment by Turkyden** [comment]
Q: 函数中的 arguments 是数组吗？类数组转数组的方法了解吗？

A：不是，属于鸭子类型的范畴，长得像数组

可使用一下方法转成数组：

- 展开表达式 ...
- Arrat.from
- Array.prototype.slice(arrayLike)

**Comment by Turkyden** [comment]
Q：说下对 JS 的了解吧？

A：2015（ES6）动态语言，以原型为主要特性，语言标准部分（ECMAScript）+ 宿主环境部分

**Comment by Turkyden** [comment]
Q: 用过 TypeScript 吗？它的作用是什么？

A: 是 JS 的超集，拥有 ES 的最新语法特性，静态类型，适合大型工程团队协作，类型推断提升代码质量。
