### ISSUE TITLE
高频考点之 CSS 篇

### ISSUE THREAD

**Issue by turkyden** [turkyden/turkyden#18]
## 高频考点

- [ ] 写代码：css div 垂直水平居中，并完成 div 高度永远是宽度的一半（宽度可以不指定）
- [ ] 请你讲一讲 CSS 的权重和优先级
- [ ] 介绍 Flex 布局，flex 是什么属性的缩写
- [ ] CSS 怎么画一个大小为父元素宽度一半的正方形
- [ ] CSS实现自适应正方形、等宽高比矩形
- [ ] 实现两栏布局的方式
- [ ] 实现三列布局的方式
- [ ] CSS 动画有哪些
- [ ] 用 css2 和 css3 分别写一下垂直居中和水平居中
- [ ] visibility 和 display 的差别（还有opacity)
- [x] opacity 可以有过渡效果嘛？
- [ ] BFC 与 IFC 区别
- [ ] BFC 会与 float 元素相互覆盖吗？为什么？举例说明
- [ ] 了解 box-sizing 吗？
- [ ] 什么是 BFC
- [x] 了解盒模型吗？
- [ ] 说一下你知道的 position 属性，都有啥特点？
- [ ] 两个 div 上下排列，都设 margin，有什么现象？
- [ ] 清除浮动有哪些方法？

## 参考

- [字节跳动最爱考的前端面试题：CSS 基础](https://juejin.cn/post/6936913689115099143#heading-40)

**Comment by Turkyden** [comment]
Q: 盒子模型

A：盒子模型可以从 F12 控制台中看出，其主要包括 4 个属性 `外边距 margin` `内边距 padding`  `边 border` `内容区 content`
