### ISSUE TITLE
浏览器调试与 React 应用性能优化

### ISSUE THREAD

**Issue by turkyden** [turkyden/turkyden#31]
https://blog.asayer.io/the-definitive-guide-to-profiling-react-applications

**Comment by Turkyden** [comment]
![image](https://user-images.githubusercontent.com/24560160/116438376-f6831c80-a880-11eb-853c-2c7bff5024ac.png)

![image](https://user-images.githubusercontent.com/24560160/116438399-fbe06700-a880-11eb-8cf9-e22c68439ec5.png)
