### ISSUE TITLE
32 个手写 JS 基础题

### ISSUE THREAD

**Issue by turkyden** [turkyden/turkyden#32]
- [x] 数组扁平化
- [x] 数组去重
- [x] 类数组转化成数组
- [ ] Array.prototype.filter
- [ ] Array.prototype.map
- [ ] Array.prototype.forEach
- [ ] Array.prototype.reduce
- [ ] Array.prototype.apply
- [ ] Array.prototype.call
- [ ] Array.prototype.bind
- [ ] debounce 防抖
- [ ] throttle 节流
- [ ] 函数科里化
- [ ] new
- [ ] instandof
- [ ] extend 原型继承
- [ ] Object.is
- [ ] Object.assign
- [x] deepClone 深拷贝
- [ ] Promise
- [ ] Promise.all
- [ ] Primise.race
- [ ] Promise 并发限制
- [ ] JSONP
- [x] Ajax
- [ ] Event 事件发布订阅模块
- [ ] 图片懒加载
- [x] 滚动加载
- [ ] 渲染几万条数据不卡住页面
- [x] 打印当前页面使用了多少种元素
- [x] 字符串解析 url 参数提取

https://juejin.cn/post/6875152247714480136

**Comment by Turkyden** [comment]
字符串解析 url 参数提取

```js
const getURLParameters = (url) => url.match(/^[?&]+/g)
  reduce((p, n) => (p[n.slice(0, n.indexOf('='))] = n.slice(n.indexOf('=') + 1), p), {})
```

```js
const parameters = getURLParameters('https://www.foo.com?name=ddj&age=18');
console.log(parameters);
```

**Comment by Turkyden** [comment]
## 数组去重

```js
const unique = (arr) => Array.from(new Set(arr));
// 
```

**Comment by Turkyden** [comment]
数组扁平化

```js
const flatten = (arr) => arr.reduce((p, n) => 
  Array.isArray(n) ? flatten(n) : p.concat(n)
)
```

**Comment by Turkyden** [comment]
类数组转换成数组

```js
Array.from(document.querySelectorAll('div'))
```

**Comment by Turkyden** [comment]
> 判断是否是 Array 类型？

- Object.prototype.toString.call([]) === [object Array]
- Array.isArray([]) === true
- [] instanceof Array === true
- [].constructor.name === 'Array'
