### ISSUE TITLE
Web Worker 线程

### ISSUE THREAD

**Issue by turkyden** [turkyden/turkyden#36]
> 知道 Web Worker 线程吗？

Javascript 是单线程模型，为了更高效的利用计算资源，现代浏览器提供了 Web Worker 使得 Javascript 主线程能够创建 Worker 线程。有以下几个特点：

- **同源限制**：分配给 Worker 线程运行的脚本文件，必须与主线程的脚本文件同源。
- **消息通信**：Worker 线程和主线程不在同一个上下文环境，它们不能直接通信，必须通过消息完成。
- **DOM 限制**：Worker 无法读取主线程所在网页的 DOM，也无法使用 document / window 这些对象。
- **脚本限制**：Worker 不能使用 `alert()` `confirm` 这些方法，但可以使用 XMLHttpRequest 发送请求。
- **文件读写**：Worker 不能读取本地文件 `file://`，他所加载的脚本必须来自网络

**Comment by Turkyden** [comment]
> 应用场景有哪些呢？

使用 Worker 线程完成轮询，每秒钟请求一次数据，和缓存对比，如果有变化，则通过事件通知主线程。**心跳检测**
