### ISSUE TITLE
SPA 前端无侵入二次开发解决方案

### ISSUE THREAD

**Issue by turkyden** [turkyden/turkyden#39]
首先，对于以 SaaS 软件即服务的厂商来说，二开是一个绕不开的话题。传统方式开发，需要客户以及各个 BU 向总部这边提二开流程，评估人天，开发排期，功能验收，版本备案，最后交付已经是几周后的事情了，成本非常高。

那么可以得出以下公式：

```text
二开系统 = 标准系统 v1.0 -> (标准系统 v1.0 + 特性 v0.0.1 (改了某个按钮的颜色))
```

以 React 技术栈为核心的 SPA 单页应用给我们带来契机。React 的心智模型里，组件是基本单位，系统是由布局组件，页面组件，UI 组件等等这些大大小小，粒度不同的组件堆叠嵌套而成。既然 React 的基本单位是组件，那么系统二开相当于组件二开，只要能对组件这一单位进行彻底二开，那么理论上就能对**整个系统进行彻底二开**。

现在我们只需要将注意力聚焦于组件层面。众所周知，React 的精髓可以用以下公式表示：

```js
View = fn(props)
```

对于不同的二开需求，可大致分成三大类，这三大类基本覆盖了大多数二开场景。

复写：

```js
View = fn(newProps)
```

重构：

```js
View = newFn(props)
```

新页面：

```js
Root = () => (
  <Router>
    <Route name='app' path='/main/app/page/:uuid' component={View} />
  </Router>
)
```

### 核心

思路有了，如何实现以上设想呢？

- 组件代理：无侵入
- 发布订阅：可拔插
- No Bundle：云开发

代理模式（Proxy Pattern）是关于软件工程最佳实践的设计模式之一，**组件代理** 即是脱胎于此。

乐观一点讲，直接在 SaaS 系统中在线编码，修改 SaaS 本身，甚至想法再大一点就是再造一个业务系统也是可以的。

发布订阅（Publish Subscribe）是软件架构中的一种消息通信范式。那么可以得出以下公式：

```text
二开系统 = 标准系统 + SDK + 无侵入二开代码片段（特性 v0.0.1，特性 v0.0.2 ...)
```

### 难点

> 如何解决包过大的问题？

拆分注册代码与业务代码，缩减二开代码体积，实现二开代码按需加载。

- 注册代码：需要前置加载，负责将二开代码片段注册至全局变量中，并通过 uuid 区分每一次的二开特性
- 业务代码：承载实际二开业务逻辑，封装了高阶组件用于异步获取业务代码，实现类似 react-loable 的按需加载效果。

> 二开物料素材与案例如何做版本管理？

Git

> 云开发的 Web IDE 中如何增加代码提示？

Monaco

![ecode 架构图](https://user-images.githubusercontent.com/24560160/117848398-d8bcab00-b2b5-11eb-83d8-a58eee656009.png)

**Comment by Turkyden** [comment]
提效降本

SaaS 产品交付实施成本是这样核算的：

一个二开功能点平均每个 EBU 提到总部这边是：5个人/天

我们沉淀了 200 个案例、物料，下载量是 5000 次

1000 人天

**Comment by Turkyden** [comment]
> 你能现场手写一个组件组件代理么？

**Comment by Turkyden** [comment]
![p19s1](https://user-images.githubusercontent.com/24560160/122703859-0fa6b900-d285-11eb-8d8d-ccbe8e649559.gif)

**Comment by Turkyden** [comment]
![image](https://user-images.githubusercontent.com/24560160/122728797-0defec00-d2ab-11eb-91d6-418659963d16.png)

**Comment by Turkyden** [comment]
> 如何选中组件？

可视化状态下 ecode 重写组件 -> EditorComponentWrap 高阶组件包裹 -> 高亮显示 -> 触发右侧 FormEditor

> 实时修改，如何联动？

FormEditor -> editorStore 共享状态 -> EditorComponentWrap -> newProps

**Comment by Turkyden** [comment]
## 组件 -> FormEditor

ecode.refactor(Button) ->  EditorComponentWrap ->Hover Highlight -> editorInstance.reload(EcId, newProps)

## FormEditor -> 组件

FormEditor -> editorComponentWrapInstance.reload(EcId, newProps)

**Comment by Turkyden** [comment]
# SPA 无侵入二开与低代码探索实践

- S 环境
 - 什么是二开？
 - 业务痛点
- T 目标
 - 业务提出三个需求（无侵入，可拔插，云开发）
 - 做生态
 - 降本提效
- A 行为
 - 组件代理（实现原理）
 - SDK（如何编写二开代码？）
 - Web IDE（@babel/standalone ES6 => ES5）
 - 可视化编辑（出码）
 - 物料生产（imgcook）
- R 结果
 - 方案顺利落地
 - 内部培训 10 场
 - 物料素材 500+

如何提升自己？

- 做分享
- 写 Demo
- 读源码
- MDN
- 大佬公众号（云谦，印记中文）

亮点：

负责：SDK 编写，Web IDE 打包构建，物料素材

难点：

因为我们是做工程，不是搞科研，做工程就是不断地爬坑，积累经验的过程，只能说爬过的坑过程中的一些思考，平常大部分时间都是在堆业务，解决方案是从大量的业务中提炼出来的，最后又会回到业务中去，服务业务。

比如：

1）我们所有代码进行前置加载了之后，导致二开代码量过大，影响 SPA 应用首屏性能。

解决方案：按需加载，类似 react/loadble 的方式，异步的引入二开业务代码片段，前置加载只负责注册，不承载具体二开业务。

2）是否需要使用 Node 服务对二开代码进行 bundle ？

解决方案: No Bundle，尽可能让开发体验近似于源码开发，将 ES6 JSX 在线转译成 ES5，通过类似 loadjs 的方式引入第三方 umd 包。

3）如何定位组件？

开始使用 url 路径和组件内部各项 Props 进行定位，后面对标准业务的组件统一加了一个唯一标识，用于二开时候对组件的定位和判断。比如：同一个页面下的两个一模一样的按钮，如何区分他们，然后进行定制化？

存在问题：

- 版本管理没有用 Git 和 Diff
- 无法直接使用第三方外部 npm 包
- 无 HMR 热更新，无法实时预览开发，每次保存都需要手动刷新页面

**Comment by Turkyden** [comment]
> 如何实现代码智能提示？

```js
monaco.languages.registerCompletionItemProvider('javascript', {
    provideCompletionItems: function(model, position) {
        // console.log('provideCompletionItems');
        return {
          suggestions:  [
             {
               label: 'React',
               kind: monaco.languages.CompletionItemKind.Keyword,
               insertText: 'React',
               documentation: "React 库语法提示"
             },
          ]
        };
    }
  });
```

**Comment by Turkyden** [comment]
> 拖拽落点高亮如何实现？

![luodian](https://user-images.githubusercontent.com/24560160/124061202-0c6bb400-da61-11eb-87b7-07886c186357.gif)

找到距离鼠标最近的元素，后面插入带高亮样式的 span 标签

**Comment by Turkyden** [comment]
后期待优化的地方？

- 
- 多人实时编辑，借鉴钉钉文档，腾讯文档，采用 OT 算法处理多人操作冲突
- 版本控制，等公司基础设施切换至 git 才能改进
