### ISSUE TITLE
Webpack vs Rollup vs Vite

### ISSUE THREAD

**Issue by turkyden** [turkyden/turkyden#46]
> 说一下打包构建器吧？用过哪些？

- Webpack: 处理依赖将多个模块 bundle 到一起，包括 CSS, HTML, 图片资源等，适合前端工程化
- Rollup: ES 转换，模块解析，适用于 JS 类库的研发，比如 Vue, umi 之类的
- Vite：基于浏览器 ES Module 的支持，跳过打包，加速开发，构建生产阶段仍然使用 Rollup

> HRM 热模块替换怎么解决？

> Tree Shaking 按需加载原理？

> Vite 中的缓存策略？

- 源码模块：协商缓存 `304 Not Modified`
- 依赖模块：强缓存 `Cache-Control: max-age=31536000,immutable`

**Comment by Turkyden** [comment]
![image](https://user-images.githubusercontent.com/24560160/119782184-70e5a180-befe-11eb-81e5-76da1dcf3f6b.png)

![image](https://user-images.githubusercontent.com/24560160/119782201-75aa5580-befe-11eb-84af-474c2cdf54ff.png)
