### ISSUE TITLE
ECode 低代码无侵入二次开发平台

### ISSUE THREAD

**Issue by turkyden** [turkyden/turkyden#49]
# ECode 低代码无侵入二次开发平台

ECode 是泛微 e-cology 9.0 推出的新功能，其本质上是为了解决传统二次开发过程中面临的问题，实现二次开发的**降本提效**。

## 大纲

- 定义
- 背景
- 应用场景
- 常用功能
- 可视化编辑
- 云商店
- 相关资料

### 产品简介

泛微 e9 系统是基于 B/S 架构，前后端分离的 SPA（Single Page Application）单页应用，以往做 UI 定制化二开时有如下痛点：

- **维护难**：对于以往做过二开的系统，后期升级过程中有可能会导致二开代码冲突或丢失
- **开发难**：需要拉取源代码至本地，搭建和配置前端开发环境
- **复用难**：二开过程中沉淀的案例，无法直接复用其他项目上

针对上述问题，ECode 平台的解决方案是：

- **无侵入**：不改变不影响标准系统源代码
- **云开发**：无需搭建本地环境，WebIDE 在线开发
- **可拔插**：二开业务案例、组件、模板、以物料包的形式沉淀下来，通过泛微云商店流转

### 应用场景

- **复写**：能够使开发者基于二开业务对页面上的 UI 组件进行调整
- **重写**：自由度比复写更高，可以实现对 UI 组件的完全替换
- **新页面**：可以在线编写新的页面，并通过路由访问
- **门户元素**：无侵入的方式注册自定义门户元素

### 可视化编辑

可视化编辑是基于 ECode 平台拓展延申的新特性，目的是降低二开上手难度，让**非专业开发岗**的同学参与进来。

![p19s1](https://user-images.githubusercontent.com/24560160/122703859-0fa6b900-d285-11eb-8d8d-ccbe8e649559.gif)

**Comment by Turkyden** [comment]
> # ECode 低代码无侵入二次开发平台
> ## 大纲
> * 定义：是什么
> * 用途：能做什么？
> * 背景：ecode VS 传统二开
> * 应用场景
> * 实操
> * 可视化编辑
> 
> ### 定义
> ECode 是泛微 e-cology 9.0 推出的新功能，其本质上是为了二次开发的**降本提效**，解决传统二次开发过程中面临的痛点问题。

**Comment by Turkyden** [comment]
## 演示环境

http://sysengine.e-cology.com.cn/
