### ISSUE TITLE
大厂面试真题

### ISSUE THREAD

**Issue by turkyden** [turkyden/turkyden#6]
## 饿了么一面

- 自我介绍，说说你做的项目和亮点，以及难点
- 然后紧接着问和项目相关的问题，怎么做的，架构为什么这么做，有没有改进的空间
- js 编译原理，介绍下 AST
- 事件循环机制，宏任务，微任务
- node 是单线程，为什么能处理高并发
- node 事件循环机制
- 跨域的解决方式，当然主要的就是 jsonp cors 这两种了
- 缓存机制，主要是问 304 和 强缓存
- web 安全， 主要是 xss csrf
- node 错误处理
- node 服务进程守护是如何做的。pm2？（不行的）
- koa 的中间件机制是什么，解决了什么问题，如何实现
- 如何理解前后端分离？（这里聊了得十分钟）
- react ssr 实现的难点
- react ssr 如何区分服务端环境还是客户端环境
- 多实例如何保存登录态，也就是 session 如何存储
- 快应用和微信小程序的底层机制区别
- 常用设计模式有哪些，具体应用场景是什么
- 数据库死锁如何解决
- 介绍下消息队列以及应用
- 说说对 mvvm 的理解

**Comment by Turkyden** [comment]
钉钉文档

···js
/** 1. 信号灯控制器
用 React 实现一个信号灯（交通灯）控制器，要求：
1. 默认情况下，
  1.1. 红灯亮20秒，并且最后5秒闪烁
  1.2. 绿灯亮20秒，并且最后5秒闪烁
  1.3. 黄灯亮10秒
  1.4. 次序为 红-绿-黄-红-绿-黄
2. 灯的个数、颜色、持续时间、闪烁时间、灯光次序都可配置，如：
   lights=[{color: '#fff', duration: 10000, twinkleDuration: 5000}, ... ]
*/

import React from 'react'
import ReactDOM from 'react-dom'
class TrafficLightItem extends React.Component {
}
```

```js
/** 2. 寻找特定 IP
IPV4 的 IP 地址是32位的二进制数，为增强可读性，通常我们以8位为1组进行分割，
用十进制来表示每一部分，并用点号连接，譬如 192.168.1.1。显然，存在这样的 IP 地址，
0到9十个数字各出现一次。具备这样特征的 IP 地址里，表示成二进制数时，二进制数左右对称
（也就是“回文”，表示成32位二进制不省略0）的情况有几种，分别是哪些？要求性能尽可能高
*/
```

**Comment by Turkyden** [comment]
- 天花板，有更多挑战，成就和学习
- 直接说薪资
- hooks 开源，你做了什么 external，
- 个人优点：Typescript，Redux，Antd Pro，Webpack，了解 Node

**Comment by Turkyden** [comment]
分享一下大厂的社招面试题吧。

一面：
1. Event Loop
2. 封装 FetchAPI，要求超时报错的同时，取消执行的 promise，而不是继续执行
3. arcGis 应用
4. 网站重构怎么重构的?
5. 原型链及 6 种继承优劣，js 多态实现
6. 前端优化的方式，强缓存和协商缓存的区别，HTTP0.9,1.0,1.1,2.0,3.0 的特点和对队头阻塞的解决，QUIC 是基于 TCP 的吗？
7. webRTC 的特点
8. EventSouce 和长轮询的差别？WebSocket 是怎么保持的长连接？
9. Sass，双飞翼布局外其他的 flex,grid,圣杯,传统浮动布局
10. BFC/IFC，justify-content 作用, transform 是否会调用 GPU
11. webgl 问了管线流程。且 EL SL 中，片元着色器和顶点着色器的基本应用。
12. requestAnimationFrame 是否会被阻塞，rAF 阶段是在 dom 渲染前还是渲染后？是否用过 requestIdleCallback？React Fiber 架构中，迭代器和此函数结合的优势？
13. canvas 常见 API，postMessage 和 worker 的结合有使用过吗？
14. 说下 virtual dom 在 vue 和 react 的区别？diff 算法有什么不同？为什么 vue 叫渐进式的？
二面 webpack:
1. 资源优化的方式
2. CommonJS和ES6&nbsp;Module的区别，Tree Shaking 的 3 个使用场景。
3. 什么是依赖树？
4. 什么是AST，有没有用过 recast？
5. 什么是热更新？怎么实现热模块替换？HMR的原理？你如何设计热模块替换？和前端的 router 有什么区别？提示：location hash 和 history。
6. 记不记得浏览器渲染原理，重绘和重排 / 回流的区别，GC 的两种类型是什么？
7. DLLplugin 的好处是什么？
8. 每次最小更新该如何做？[name]@[chunkhash].js, contenthash 是什么？loader 和 plugin 哪个先开启引入？runtime 和 manifest 分别是什么？记不记得 service worker，每次更新是更新全部，还是只更新 manifest？
9. webpack中plugin和loader的区别，有没有自己写过plugin，作用是什么？
10. MVV*和 MVN*是指什么？使用过 SSR 吗？
11. 如何开发移动端项目？
12. 重构网站的思路
13. TypeScript 中装饰器是怎么实现的？能不能讲下元编程，就是 Proxy 和 Reflect 的应用？有没有自己写过入侵的测试框架，自己实现 Hook 管理了吗？
